vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/competent
            upload_destination: '%kernel.project_dir%/public/images/competent'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

